###Работа с Pandas

In [ ]:
import numpy as np

Генерация случайной матрицы

In [ ]:
X = np.random.normal(loc=1, scale=10, size=(1000,50))

In [ ]:
X

array([[  9.59886107,  17.43172934,   9.16304141, ...,  -7.81735322,
          6.08536703,   5.1504996 ],
       [  8.25384109,   4.80430529,   0.62466806, ...,  -0.9552125 ,
         11.65390621,   5.8234809 ],
       [ 18.16460664,  -2.40113605,  -5.5489461 , ...,  -8.05215865,
        -11.1484656 ,  -5.74651653],
       ...,
       [  9.78387026,  -9.99717493,  -0.54422849, ...,   0.51690314,
         10.99498021,  10.35548377],
       [ 10.858158  ,  12.83305369,  -4.36038539, ...,  25.78323395,
         16.18705409,   5.90874456],
       [  5.2962161 ,  -6.13886533,   6.53214524, ...,  -4.03010215,
          0.3015772 ,   9.89062759]])

Нормировка матрицы

In [ ]:
m = np.mean(X, axis=0)
std = np.std(X, axis=0)

In [ ]:
X_norm = (X - m) / std

In [ ]:
X_norm

array([[ 0.86531353,  1.66307869,  0.81687349, ..., -0.87628744,
         0.49546767,  0.38369137],
       [ 0.73198339,  0.36619565, -0.05308833, ..., -0.20213414,
         1.03843236,  0.44985101],
       [ 1.71442516, -0.37382976, -0.68210845, ..., -0.89935529,
        -1.18493045, -0.68757557],
       ...,
       [ 0.88365326, -1.15397097, -0.17218542, ..., -0.05750993,
         0.97418328,  0.89538443],
       [ 0.99014606,  1.19077774, -0.56100782, ...,  2.42471552,
         1.48044044,  0.45823313],
       [ 0.43879773, -0.75770834,  0.5488155 , ..., -0.50421873,
        -0.06848521,  0.84968522]])

Операции над элементами матрицы

In [ ]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

In [ ]:
r = np.sum(Z, axis=1)

In [ ]:
np.nonzero(r > 10)

(array([1, 4, 5]),)

Объединение матриц

In [ ]:
A = np.eye(3)
B = np.eye(3)

In [ ]:
AB = np.vstack((A,B))
AB

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###Задание по программированию: Предобработка данных в Pandas

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving train.csv to train.csv


In [ ]:
import io

In [ ]:
data = pd.read_csv(io.BytesIO(uploaded['train.csv']), index_col='PassengerId')

In [ ]:
data.head()

Survived  Pclass  ... Cabin Embarked
PassengerId                    ...               
1                   0       3  ...   NaN        S
2                   1       1  ...   C85        C
3                   1       3  ...   NaN        S
4                   1       1  ...  C123        S
5                   0       3  ...   NaN        S

[5 rows x 11 columns]

In [ ]:
type(data)

pandas.core.frame.DataFrame

In [ ]:
data[:4]

Survived  Pclass  ... Cabin Embarked
PassengerId                    ...               
1                   0       3  ...   NaN        S
2                   1       1  ...   C85        C
3                   1       3  ...   NaN        S
4                   1       1  ...  C123        S

[4 rows x 11 columns]

In [ ]:
data['Pclass']

PassengerId
1      3
2      1
3      3
4      1
5      3
      ..
887    2
888    1
889    3
890    1
891    3
Name: Pclass, Length: 891, dtype: int64

Для подсчета количества

In [ ]:
data['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

1. Какое количество мужчин и женщин ехало на корабле? В качестве ответа приведите два числа через пробел.

In [ ]:
data['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

2. Какой части пассажиров удалось выжить? Посчитайте долю выживших пассажиров. Ответ приведите в процентах (число в интервале от 0 до 100, знак процента не нужен), округлив до двух знаков.

In [ ]:
counts_male, counts_female = data['Survived'].value_counts()

In [ ]:
counts_male_prc = counts_male / data['Survived'].count() * 100

In [ ]:
counts_female_prc = counts_female / data['Survived'].count() * 100

In [ ]:
round(counts_male_prc, 2), round(counts_female_prc, 2)

(61.62, 38.38)

3. Какую долю пассажиры первого класса составляли среди всех пассажиров? Ответ приведите в процентах (число в интервале от 0 до 100, знак процента не нужен), округлив до двух знаков.

In [ ]:
type(data.Pclass[1])

numpy.int64

In [ ]:
data.Pclass[1]

3

In [ ]:
data[data['Pclass'] > 1]

Survived  Pclass  ... Cabin Embarked
PassengerId                    ...               
1                   0       3  ...   NaN        S
3                   1       3  ...   NaN        S
5                   0       3  ...   NaN        S
6                   0       3  ...   NaN        Q
8                   0       3  ...   NaN        S
...               ...     ...  ...   ...      ...
885                 0       3  ...   NaN        S
886                 0       3  ...   NaN        Q
887                 0       2  ...   NaN        S
889                 0       3  ...   NaN        S
891                 0       3  ...   NaN        Q

[675 rows x 11 columns]

In [ ]:
first_class = data[data['Pclass'] == 1]['Pclass'].count() / data['Pclass'].count() * 100

In [ ]:
round(first_class, 2)

24.24

4. Какого возраста были пассажиры? Посчитайте среднее и медиану возраста пассажиров. В качестве ответа приведите два числа через пробел.

In [ ]:
data['Age'].unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [ ]:
mean_age = data['Age'].mean()

In [ ]:
mediana_age = data['Age'].median()

In [ ]:
mean_age, mediana_age 

(29.69911764705882, 28.0)

5. Коррелируют ли число братьев/сестер/супругов с числом родителей/детей? Посчитайте корреляцию Пирсона между признаками SibSp и Parch.

In [ ]:
data[['SibSp','Parch']]

SibSp  Parch
PassengerId              
1                1      0
2                1      0
3                0      0
4                1      0
5                0      0
...            ...    ...
887              0      0
888              0      0
889              1      2
890              0      0
891              0      0

[891 rows x 2 columns]

In [ ]:
data[['SibSp','Parch']].corr()

SibSp     Parch
SibSp  1.000000  0.414838
Parch  0.414838  1.000000

6. Какое самое популярное женское имя на корабле? Извлеките из полного имени пассажира (колонка Name) его личное имя (First Name)

In [ ]:
female_names = data.loc[data['Sex'] == 'female', 'Name']

In [ ]:
female_names = female_names.str.split(',', expand=True)

In [ ]:
female_names.shape

(314, 2)

In [ ]:
female_names.columns = ['first_name', 'other']

In [ ]:
female_names

first_name                                        other
PassengerId                                                        
2              Cumings   Mrs. John Bradley (Florence Briggs Thayer)
3            Heikkinen                                  Miss. Laina
4             Futrelle           Mrs. Jacques Heath (Lily May Peel)
9              Johnson     Mrs. Oscar W (Elisabeth Vilhelmina Berg)
10              Nasser                  Mrs. Nicholas (Adele Achem)
...                ...                                          ...
881            Shelley          Mrs. William (Imanita Parrish Hall)
883           Dahlberg                           Miss. Gerda Ulrika
886               Rice               Mrs. William (Margaret Norton)
888             Graham                         Miss. Margaret Edith
889           Johnston               Miss. Catherine Helen "Carrie"

[314 rows x 2 columns]

In [ ]:
female_names['first_name'].value_counts()

Andersson    6
Baclini      4
Sage         3
Ford         3
Brown        3
            ..
Nilsson      1
Kantor       1
Spedden      1
Slayter      1
Johnston     1
Name: first_name, Length: 258, dtype: int64

In [ ]:
female_names = data[data['Sex'] == 'female']['Name']

In [ ]:
male_names = data[data['Sex'] == 'male']['Name']

In [ ]:
female_names.head()

PassengerId
2     Cumings, Mrs. John Bradley (Florence Briggs Th...
3                                Heikkinen, Miss. Laina
4          Futrelle, Mrs. Jacques Heath (Lily May Peel)
9     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
10                  Nasser, Mrs. Nicholas (Adele Achem)
Name: Name, dtype: object

In [ ]:
male_names.head()

PassengerId
1           Braund, Mr. Owen Harris
5          Allen, Mr. William Henry
6                  Moran, Mr. James
7           McCarthy, Mr. Timothy J
8    Palsson, Master. Gosta Leonard
Name: Name, dtype: object

---


###Задание по программированию: Важность признаков

Реализация в Scikit-Learn

In [ ]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier

In [ ]:
X = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([0, 1, 0])

In [ ]:
clf = DecisionTreeClassifier()

In [ ]:
clf.fit(X, y)

DecisionTreeClassifier()

In [ ]:
importances = clf.feature_importances_ #важность признаков

In [ ]:
importances

array([0., 1.])

In [ ]:
np.isnan(X)

array([[False, False],
       [False, False],
       [False, False]])

In [ ]:
data_D3 = data[['Pclass','Fare','Age','Sex','Survived']]

In [ ]:
data_D3.head()

Pclass     Fare   Age     Sex  Survived
PassengerId                                         
1                 3   7.2500  22.0    male         0
2                 1  71.2833  38.0  female         1
3                 3   7.9250  26.0  female         1
4                 1  53.1000  35.0  female         1
5                 3   8.0500  35.0    male         0

In [ ]:
data_D3.shape

(891, 5)

Пропущенные значения

In [ ]:
data_D3_cl = data_D3.dropna()

In [ ]:
data_D3_cl.head()

Pclass     Fare   Age     Sex  Survived
PassengerId                                         
1                 3   7.2500  22.0    male         0
2                 1  71.2833  38.0  female         1
3                 3   7.9250  26.0  female         1
4                 1  53.1000  35.0  female         1
5                 3   8.0500  35.0    male         0

In [ ]:
data_D3_cl.shape

(714, 5)

Замена строк на целые значения

In [ ]:
data_D3_cl.Sex.replace(['male','female'],[1,0], inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)


In [ ]:
data_D3_cl.head()

Pclass     Fare   Age  Sex  Survived
PassengerId                                      
1                 3   7.2500  22.0    1         0
2                 1  71.2833  38.0    0         1
3                 3   7.9250  26.0    0         1
4                 1  53.1000  35.0    0         1
5                 3   8.0500  35.0    1         0

In [ ]:
Y_train = data_D3_cl['Survived']

In [ ]:
X_train = data_D3_cl.drop(columns='Survived',axis=1)

In [ ]:
X_train.head()

Pclass     Fare   Age  Sex
PassengerId                            
1                 3   7.2500  22.0    1
2                 1  71.2833  38.0    0
3                 3   7.9250  26.0    0
4                 1  53.1000  35.0    0
5                 3   8.0500  35.0    1

In [ ]:
clf_titanic = DecisionTreeClassifier(random_state=241)

In [ ]:
clf_titanic.fit(X_train, Y_train)

DecisionTreeClassifier(random_state=241)

In [ ]:
importances_titanic = clf_titanic.feature_importances_

In [ ]:
importances_titanic 

array([0.14000522, 0.30343647, 0.2560461 , 0.30051221])

In [ ]:
# Fare & Sex - the most important

---

Попытка предсказать (разделение на классы)

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving test.csv to test.csv


In [ ]:
X_test = pd.read_csv(io.BytesIO(uploaded['test.csv']), index_col='PassengerId')

In [ ]:
X_test.shape

(418, 10)

In [ ]:
X_test = X_test[['Pclass','Fare','Age','Sex']]

In [ ]:
#X_test = X_test.dropna()

In [ ]:
#X_test.shape

(331, 4)

In [ ]:
X_test.Sex.replace(['male','female'],[1,0], inplace=True)

In [ ]:
X_test.head()

Pclass     Fare   Age  Sex
PassengerId                            
892               3   7.8292  34.5    1
893               3   7.0000  47.0    0
894               2   9.6875  62.0    1
895               3   8.6625  27.0    1
896               3  12.2875  22.0    0

In [ ]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 892 to 1309
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Pclass  418 non-null    int64  
 1   Fare    418 non-null    float64
 2   Age     418 non-null    float64
 3   Sex     418 non-null    int64  
dtypes: float64(2), int64(2)
memory usage: 16.3 KB


In [ ]:
X_test.dtypes

Pclass      int64
Fare      float64
Age       float64
Sex         int64
dtype: object

In [ ]:
X_test = X_test.fillna(X_test.mean())

In [ ]:
target = clf_titanic.predict(X_test)

In [ ]:
target

array([0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [ ]:
submission = pd.DataFrame(data=X_test.index, columns=["PassengerId"])
#submission.to_csv('submission.csv', index=False)


In [ ]:
submission['Survived'] = target

In [ ]:
submission.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         1
3          895         1
4          896         0

In [ ]:
submission.to_csv('submission.csv', index=False)  #0.71 на kaggle.com



---

